name: Web

on:
  push:
    paths:
      - 'packages/web/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: yarn install
        run: yarn
        env:
          CI: true
      - name: yarn test:web
        run: yarn test:web
